### ISSUE TITLE
Issues with word blacklisting

### ISSUE THREAD

**Issue by TeraBaito** [TeraBaito/jaidens-discord-utilities#4]
**OFFENSIVE WORDS AHEAD, READ WITH DISCRETION**

Blacklisting is yet one of the simplest yet most troublesome systems I've done. I will herein be writing all issues that come along with it as time progresses and member/self reports are made, up until everything possible is solved. 

- I will add checkmarks so progress can be publicly seen.
- I will add numbers to each issue so I can mention them as I commit.
- I may also add keywords like `WONTFIX` to aid myself and others on what I do or not do.
- Pull requests would be gladly appreciated.

[Link to blacklisting function](https://github.com/TeraBaito/jaidens-discord-utilities/blob/master/src/handlers/functions.js#L121)

Syntax:
`c` -> normal character
`B` -> blacklisted word
`*` -> 1 or more occurences
`***` -> 1 to undefined chars (basically c* but emphasizes on undefined count)
The issues are as follows:

- [x] 1. Bot blacklisting substrings in a word (such as `cum` in `document`)
- [x] 2. Bot not blacklisting UPPERCASE words
- [x] 3. Bot blacklisting words of syntax `c*B`
- [x] 4. Bot not blacklisting syntax `B ***` but blacklisting `B`
- [x] 5. Blacklisting is easily bypassable by putting an extra character after/before it (e.g. "cum.")
- [x] 6. It blacklists "circumstance" for including `***cums***"`, and therefore every `***Bs***`
- [x] 7. Spaces get a lil fucky on what it removes and what it doesn't (I'm yet to know any technical details, but I do know they're very propense for some weird shit to happen
- [x] 8. Adding symbols like `*` `+` `-` will reflect on the RegExp, I'll need to escape them when adding them in the JSON
- [x] 9. Message splitting made pluriword entries (e.g. "fuck jaiden") not work (of course)
- [x] 10. Symbol checking will blacklist, even if it doesn't exactly match ^ to $ (e.g. "incum.", but not "incum")

**Comment by TeraBaito** [comment]
7ce4d0d fixes all 2, 3 and 4.

**Comment by TeraBaito** [comment]
19e87c9 fixes 5 (planning on refactoring RegExp)

**NOTE:** Putting symbols in the JSON might break the RegExp (it evals as RegExp syntax, not as actual chars) (you can escape but I'm yet to know how without the JSON erroring)

**Comment by TeraBaito** [comment]
**TODOs** | 4/7
- [x] Splitting message by spaces, so I don't have to rely on space filtering and it can be (overall) better
- [x] Adding checks that will append a `\\` to special characters on _addword_ and _removeword_ commands
- [x] ~Making the pluralizer only work in word ends (message splitting might fix this)~ | removed pluralizer, too troublesome

**Comment by TeraBaito** [comment]
14ee153197852696a87b66ac6a931176c8fa51e0 fixes 6 and 7 (next up is the `\\` appending)

**Comment by TeraBaito** [comment]
3c8f1d551319eeffbf4dfff0d8066566c824eb77 fixes 8
800f40f6e826ee5d119e1deb323fd47f7cc59a6e fixes 9

**Comment by TeraBaito** [comment]
After so much time, 970bb97 fixes 10. All issues resolved as of now.

**Comment by TeraBaito** [comment]
Closing until future issues
